import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import { AuthProvider } from './context/AuthContext'

export const metadata: Metadata = {
  title: 'Tulospalvelu JM-kyykka.fi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fi">
      <body>
        <div className="layout">
          <Navbar />
          <AuthProvider>{children}</AuthProvider>
          <Footer />
        </div>
      </body>
    </html>
  )
}
